language: bash
services:
- docker
cache:
  directories:
  - "${HOME}/bin"
install:
- make ensure-checkmake ensure-shellcheck ensure-shfmt
script:
- make lint
- git diff --exit-code
- git diff --cached --exit-code
- make test
