language: __stevonnie__
dist: xenial
group: edge
services:
- docker
cache:
  directories:
  - "${HOME}/bin"
addons:
  apt:
    packages:
    - python3-virtualenv
env:
  global:
  - RUNDIR=$TRAVIS_BUILD_DIR/tmp/travis-run.d
before_install:
- travis_retry python3 -m virtualenv --python=python3 .venv
- source .venv/bin/activate
install:
- make deps
script:
- make lint
- touch bin/tfw
- make USAGE.md
- git diff --exit-code
- git diff --cached --exit-code
- make test
- make sysseed
- make systest
