language: python
python:
- 3.5.2
- 3.6.5
services:
- docker
cache:
  directories:
  - "${HOME}/bin"
install:
- make deps
script:
- make lint
- touch bin/tfw
- make USAGE.md
- git diff --exit-code
- git diff --cached --exit-code
- make test
