language: __stevonnie__
dist: xenial
group: edge
services:
- docker
cache:
  directories:
  - "${HOME}/bin"
addons:
  apt:
    packages:
    - python3-virtualenv
before_install:
- python3 -m virtualenv --python=python3 .venv
- source .venv/bin/activate
install:
- make deps
script:
- make lint
- touch bin/tfw
- make USAGE.md
- git diff --exit-code
- git diff --cached --exit-code
- make test
- make systest
